# Postgres/Redis backup
# We don't just back up because we have to (cough cough covenant), but
# because it's a good practice! Also, never forget that your redis data
# is persistent.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: masto-backups
  namespace: mastodon
spec:
  # Backup the database every day at 2AM
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: masto-pg-backup
            image: docker.io/bitnami/postgresql:14.2.0-debian-10-r14
            command: ["/bin/sh"]
            args: ["-c", 'pg_dump -U mastodon -h crunchy-mastodon-pgbouncer.mastodon mastodon_production > /media/seano/md0/System/k8s_persist/masto-backups/backup-$(date +"%m-%d-%Y-%H-%M").sql && find /media/seano/md0/System/k8s_persist/masto-backups -maxdepth 1 -mtime +14 -type f -exec rm -rv {} + && curl -I $CRONURL']
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mastodon-postgresql
                  key: password
            - name: CRONURL
              valueFrom:
                secretKeyRef:
                  name: uptime-cron-notification
                  key: db-backup
            volumeMounts:
            - mountPath: /media/seano/md0/System/k8s_persist/masto-backups
              name: postgres-storage
          - name: masto-redis-backup
            image: docker.io/bitnami/redis:6.2.7-debian-11-r11
            command: ["/bin/sh"]
            args: ["-c", 'cp /data/dump.rdb /media/seano/md0/System/k8s_persist/masto-backups/backup-$(date +"%m-%d-%Y-%H-%M").rdb']
            volumeMounts:
            - mountPath: /media/seano/md0/System/k8s_persist/masto-backups
              name: postgres-storage
            - mountPath: /data
              name: redis-data
          restartPolicy: Never
          volumes:
          - name: postgres-storage
            nfs:
              server: "192.168.1.44"
              path: /media/seano/md0/System/k8s_persist/masto-backups
          - name: redis-data
            persistentVolumeClaim:
              claimName: redis-data-mastodon-redis-master-0
