# Auto-account Approval job
# context: https://masto.nyc/@seano/109883742322567730
# This job auto-approves any accounts who have requested to join
# every five minutes. I would honestly LOVE to turn on open
# sign ups, but they are simply too much of a bot honeypot. 
apiVersion: batch/v1
kind: CronJob
metadata:
  name: masto-approveaccounts
  namespace: mastodon
spec:
  schedule: "5 * * 12 *"
  concurrencyPolicy: Allow
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: masto-approveaccounts
        spec:
          volumes:
            - name: assets
              persistentVolumeClaim:
                claimName: mastodon-assets
            - name: system
              persistentVolumeClaim:
                claimName: mastodon-system
          containers:
            - name: masto-approveaccounts
              image: ghcr.io/mastodon/mastodon:v4.2.10
              command: ["/bin/sh"]
              args: ["-c", "bin/tootctl accounts approve --all && wget -S --spider $CRONURL"]
              envFrom:
                - configMapRef:
                    name: mastodon-env
                - secretRef:
                    name: mastodon
              env:
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: mastodon-postgresql
                      key: password
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mastodon-redis
                      key: redis-password
                - name: CRONURL
                  valueFrom:
                    secretKeyRef:
                      name: uptime-cron-notification
                      key: accapprove
                - name: PORT
                  value: '3000'
              resources: {}
              volumeMounts:
                - name: assets
                  mountPath: /opt/mastodon/public/assets
                - name: system
                  mountPath: /opt/mastodon/public/system
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/part-of
                        operator: In
                        values:
                          - rails
                  topologyKey: kubernetes.io/hostname
          schedulerName: default-scheduler
