# Tags Updater
# We are affected by:
# https://github.com/mastodon/mastodon/issues/20230
# Soooooooo this has to exist.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: masto-indexup
  namespace: mastodon
spec:
  schedule: "0 */2 * * *"
  concurrencyPolicy: Allow
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: masto-indexup
        spec:
          volumes:
            - name: assets
              persistentVolumeClaim:
                claimName: mastodon-assets
            - name: system
              persistentVolumeClaim:
                claimName: mastodon-system
          containers:
            - name: masto-indexup
              image: ghcr.io/mastodon/mastodon:v4.2.4
              command:
                - bin/tootctl
                - search
                - deploy
              envFrom:
                - configMapRef:
                    name: mastodon-env
                - secretRef:
                    name: mastodon
              env:
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: mastodon-postgresql
                      key: password
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mastodon-redis
                      key: redis-password
                - name: PORT
                  value: '3000'
              resources: {}
              volumeMounts:
                - name: assets
                  mountPath: /opt/mastodon/public/assets
                - name: system
                  mountPath: /opt/mastodon/public/system
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/part-of
                        operator: In
                        values:
                          - rails
                  topologyKey: kubernetes.io/hostname
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
