---
# Source: mastodon/templates/deployment-web.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-nginx
  namespace: mastodon
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      volumes:
        - name: masto-nginx-config
          configMap:
            name: masto-nginx-config-prd
      containers:
        - name: mastodon-nginx
          image: nginx:1.25.4-alpine
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
            - name: masto-nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
      - name: masto-nginx-config
        configMap:
          name: masto-nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf