# This is a SANITIZED file where sensitive values have been redacted, and not in actual use. 
# This should only be used as reference. Values that need replacing surrounded by {{}}
apiVersion: v1
kind: Secret
metadata:
  name: mastodon-redis
  namespace: "mastodon"
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: mastodon
type: Opaque
data:
  redis-password: {{NEVER FORGET REDIS NEEDS BACKUPS}}
