---
# Source: mastodon/charts/redis/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: mastodon-redis
  namespace: "mastodon"
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: mastodon
